# Pytorch를 사용한 딥 러닝

## 이 노트북에서 다룰 내용
1. PyTorch 텐서 소개
2. 텐서 연산 및 기울기
3. PyTorch와 Numpy 간의 상호 운용성
4. PyTorch 문서 사이트 사용 방법

시작하기 전에 필요한 라이브러리를 설치해야 한다.

PyTorch의 설치는 운영 체제/클라우드 환경에 따라 다를 수 있다.

자세한 설치 방법은 https://pytorch.org에서 찾을 수 있다.

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio


설치가 되었다면 아래의 코드를 수행할 수 있다.

In [ ]:
import torch

## 텐서

PyTorch의 핵심은 텐서를 처리하기 위한 라이브러리다.

텐서는 숫자, 벡터, 행렬 또는 n차원 배열이다.

단일 숫자로 텐서를 생성해 보겠다.

In [ ]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.`는 `4.0`의 줄임말이다. 부동 소수점 숫자를 생성하려는 Python(및 PyTorch)을 나타내는 데 사용된다. 텐서의 `dtype` 속성을 확인하여 이를 확인할 수 있다.

In [ ]:
t1.dtype

torch.float32

더 복잡한 텐서를 만들어 보자.

In [ ]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

텐서는 각 차원을 따라 여러 차원과 다른 길이를 가질 수 있다.

텐서의 `.shape` 속성을 사용하여 각 차원의 길이를 검사할 수 있다.

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

부적절한 모양으로 텐서를 생성하는 것은 불가능하다.

In [ ]:
# Matrix
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])
t5

ValueError: expected sequence of length 3 at dim 1 (got 2)

## 텐서 연산 및 그라디언트

텐서를 일반적인 산술 연산과 결합할 수 있다.

In [ ]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

3개의 텐서를 생성했다: `x`, `w`, `b`, 모두 숫자이다.

`w` 및 `b`에는 `True`로 설정된 추가 매개변수 `requires_grad`가 있다.

  우리는 잠시 후에 그것이 무엇을 하는지 볼 것이다.

이 텐서를 결합하여 새로운 텐서 `y`를 만들어 봅시다.

In [ ]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

예상대로 `y` 값이 `3 * 4 + 5 = 17`인 텐서다.

PyTorch를 독특하게 만드는 것은 `y` w.r.t의 도함수를 자동으로 계산할 수 있다는 것이다. 
`requires_grad`가 `True`로 설정되어 있고, w와 b를 갖고 있다.

PyTorch의 이 기능을 _autograd_(자동 그라디언트)라고 한다.

도함수를 계산하기 위해 결과 `y`에 대해 `.backward` 메소드를 호출할 수 있다.

In [ ]:
# Compute derivatives
y.backward()

입력 텐서에 대한 `y`의 도함수는 각 텐서의 `.grad` 속성에 저장된다.

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


`dy/dw`는 `x`와 같은 값, 즉 `3`을 가지며 `dy/db`는 `1`의 값을 갖는다.

`x`에는 `requires_grad`가 `True`로 설정되어 있지 않기 때문에 `x.grad`는 `None`이다.

`w.grad`의 "grad"는 _gradient_의 줄임말로 도함수의 또 다른 용어이다.

_gradient_라는 용어는 벡터와 행렬을 다룰 때 주로 사용된다.

## 텐서 함수

산술 연산 외에도 `torch` 모듈에는 텐서를 생성하고 조작하기 위한 많은 기능이 포함되어 있다. 

몇 가지 예를 살펴보겠다.

In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

텐서 작업에 대한 자세한 내용은 https://pytorch.org/docs/stable/torch.html에서 확인할 수 있다.


## Numpy와 같이 사용하기

[Numpy](http://www.numpy.org/)는 Python에서 수학 및 과학 컴퓨팅에 사용되는 인기 있는 오픈 소스 라이브러리이다.

대규모 다차원 어레이에서 효율적인 작업을 가능하게 하며 다음을 포함하여 지원 라이브러리들을 가지고 있음

* 파일 I/O 및 데이터 분석을 위한 [Pandas](https://pandas.pydata.org/)
* 플로팅 및 시각화를 위한 [Matplotlib](https://matplotlib.org/)
* 이미지 및 비디오 처리를 위한 [OpenCV](https://opencv.org/)

Python의 Numpy 및 기타 데이터 과학 라이브러리에 대해 자세히 알아보려면 아래의 튜토리얼을 참고하라.

https://jovian.ai/aakashns/python-numerical-computing-with-numpy.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

Numpy 배열을 `torch.from_numpy`를 사용하여 PyTorch 텐서로 변환할 수 있다.

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

텐서의 `.numpy` 메서드를 사용하여 PyTorch 텐서를 Numpy 배열로 변환할 수 있다.

In [ ]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

PyTorch와 Numpy 간의 상호 운용성은 작업할 대부분의 데이터 세트가 Numpy 배열로 읽고 사전 처리될 가능성이 높기 때문에 필수적이다.

Numpy는 이미 다차원 숫자 데이터 작업을 위한 데이터 구조와 유틸리티를 제공하기 때문에 PyTorch와 같은 라이브러리가 필요한 이유가 궁금할 것이다. 두 가지의 주요한 이유가 있음

1. **Autograd**: 텐서 연산의 기울기를 자동으로 계산하는 기능은 딥 러닝 모델을 훈련하는 데 필수

2. **GPU 지원**: 대규모 데이터 세트 및 대규모 모델로 작업하는 동안 PyTorch 텐서 작업은 GPU(그래픽 처리 장치)를 사용하여 효율적으로 수행할 수 있음

일반적으로 몇 시간이 걸릴 수 있는 계산을 GPU를 사용하면 몇 분 안에 완료할 수 있다.